recipe/meta.yaml
See https://github.com/numpy/numpy/releases/tag/v1.12.0
=> Update to 1.12.0

recipe/meta.yaml
See https://github.com/numpy/numpy/releases/tag/v1.12.1
=> Update to 1.12.1

recipe/meta.yaml, recipe/mingw_py27.patch
Adds a patch to get extensions compile on mingw, see https://github.com/numpy/numpy/pull/9280
ping @ocefpaf
=> FIX: add mingw_py27 patch

.travis.yml, LICENSE, ci_support/fast_finish_ci_pr_build.sh, ci_support/run_docker_build.sh, circle.yml, recipe/meta.yaml
=> update openblas pin

recipe/meta.yaml
We should use conda-inspect everywhere.
=> conda-inspect

.travis.yml, ci_support/run_docker_build.sh
These can be removed in the next re-rendering. I doing a 1-time build for academic purposes.
=> force add PY34

recipe/meta.yaml
=> Build v1.8 with OpenBLAS 0.2.20

recipe/meta.yaml
=> Build v1.9 with OpenBLAS 0.2.20

recipe/meta.yaml
=> Build v1.11 with OpenBLAS 0.2.20

recipe/meta.yaml
=> Build v1.12 with OpenBLAS 0.2.20

.travis.yml, ci_support/run_docker_build.sh, conda-forge.yml, recipe/meta.yaml
See https://github.com/numpy/numpy/releases/tag/v1.14.0rc1
=> Create an rc branch and build numpy 1.14.0rc1

recipe/meta.yaml
See https://github.com/numpy/numpy/releases/tag/v1.14.0
=> update to 1.14.0

recipe/meta.yaml
See https://github.com/numpy/numpy/releases/tag/v1.14.2
=> update to 1.14.2

recipe/meta.yaml
=> Readd feature

recipe/bld.bat, recipe/f2py.bat, recipe/meta.yaml, recipe/run_test.py
=> update to 1.15.0

recipe/bld.bat, recipe/build.sh, recipe/meta.yaml
=> Fix blas linking on osx

.ci_support/linux_python2.7.yaml, .ci_support/linux_python3.6.yaml, .ci_support/linux_python3.7.yaml, .ci_support/osx_python2.7.yaml, .ci_support/osx_python3.6.yaml, .ci_support/osx_python3.7.yaml, recipe/bld.bat, recipe/build.sh, recipe/meta.yaml
=> Fix linking v1.9

.ci_support/linux_python2.7.yaml, .ci_support/linux_python3.6.yaml, .ci_support/linux_python3.7.yaml, .ci_support/osx_python2.7.yaml, .ci_support/osx_python3.6.yaml, .ci_support/osx_python3.7.yaml, .ci_support/win_c_compilervs2008python2.7.yaml, .ci_support/win_c_compilervs2015python3.6.yaml, .ci_support/win_c_compilervs2015python3.7.yaml, recipe/bld.bat, recipe/build.sh, recipe/meta.yaml
=> Fix linking for osx and win v1.11

recipe/bld.bat, recipe/build.sh, recipe/meta.yaml
=> Fix linking for osx and win v1.15

recipe/meta.yaml
closes https://github.com/conda-forge/numpy-feedstock/issues/163
Checklist
=> Fixup AARCH64, add justificiation for skipped tests.

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/osx_numpy1.14python3.6.____cpythontarget_platformosx-64.yaml, .ci_support/osx_numpy1.14python3.7.____cpythontarget_platformosx-64.yaml, .ci_support/osx_numpy1.14python3.8.____cpythontarget_platformosx-64.yaml, .ci_support/osx_numpy1.18python3.6.____73_pypytarget_platformosx-64.yaml, .drone.yml, .scripts/build_steps.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, .travis.yml, README.md, recipe/build.sh
=> Fix osx failure

README.md, recipe/bld.bat, recipe/cblas.diff, recipe/meta.yaml
=> Fix cblas detection on windows

recipe/bld.bat, recipe/f2py.bat, recipe/meta.yaml
Hopefully addresses #276, but so far only pushing into a dev label.
=> Also define entry-point on unix

.azure-pipelines/azure-pipelines-osx.yml, recipe/meta.yaml
Bot is very helpful... not
```
No error information available for version '1.23.2'.
```
=> Numpy 1.23.2

.azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_numpy1.20python3.8.____73_pypypython_implpypy.yaml, .ci_support/linux_64_numpy1.20python3.8.____cpythonpython_implcpython.yaml, .ci_support/linux_64_numpy1.20python3.9.____73_pypypython_implpypy.yaml, .ci_support/linux_64_numpy1.20python3.9.____cpythonpython_implcpython.yaml, .ci_support/linux_64_numpy1.21python3.10.____cpythonpython_implcpython.yaml, .ci_support/linux_64_numpy1.23python3.11.____cpythonpython_implcpython.yaml, .ci_support/linux_aarch64_numpy1.20python3.8.____73_pypypython_implpypy.yaml, .ci_support/linux_aarch64_numpy1.20python3.8.____cpythonpython_implcpython.yaml, .ci_support/linux_aarch64_numpy1.20python3.9.____73_pypypython_implpypy.yaml, .ci_support/linux_aarch64_numpy1.20python3.9.____cpythonpython_implcpython.yaml, .ci_support/linux_aarch64_numpy1.21python3.10.____cpythonpython_implcpython.yaml, .ci_support/linux_aarch64_numpy1.23python3.11.____cpythonpython_implcpython.yaml, .ci_support/linux_ppc64le_numpy1.20python3.8.____73_pypypython_implpypy.yaml, .ci_support/linux_ppc64le_numpy1.20python3.8.____cpythonpython_implcpython.yaml, .ci_support/linux_ppc64le_numpy1.20python3.9.____73_pypypython_implpypy.yaml, .ci_support/linux_ppc64le_numpy1.20python3.9.____cpythonpython_implcpython.yaml, .ci_support/linux_ppc64le_numpy1.21python3.10.____cpythonpython_implcpython.yaml, .ci_support/linux_ppc64le_numpy1.23python3.11.____cpythonpython_implcpython.yaml, recipe/meta.yaml
bot errored:
```
- could not hash URL template 'https://github.com/numpy/numpy/releases/download/v{{ version }}/numpy-{{ version }}.tar.gz'
```
=> numpy 1.24.0

recipe/meta.yaml
=> numpy 1.24.4

.ci_support/linux_64_numpy1.22python3.10.____cpythonpython_implcpython.yaml, .ci_support/linux_64_numpy1.22python3.9.____cpythonpython_implcpython.yaml, .ci_support/linux_64_numpy1.23python3.11.____cpythonpython_implcpython.yaml, .ci_support/linux_64_numpy1.26python3.12.____cpythonpython_implcpython.yaml, .scripts/build_steps.sh, recipe/meta.yaml, recipe/patches/0001-fix-sanity-check-for-d-cross-compilation.patch, recipe/patches/0002-Make-sure-machine_info_can_run-isn-t-called-on-incom.patch
Based on #321, adding some necessary (but non-obvious) fixes.
=> numpy v2.0.1
