recipe/bld.bat
recipe/meta.yaml

Fixes https://github.com/conda-forge/numpy-feedstock/issues/1
Pins OpenBLAS to 0.2.18 as that is how the filename is versioned.
Also, switch to the 200 build number range. 101 up to 200 will be reserved for `noblas`. Basically, build number is playing a big role in how this gets installed if nothing is pinned so we need to do this to keep OpenBLAS as the default. In the future (next NumPy release which should be soon), we can make `noblas` start at 100.

Pin OpenBLAS to 0.2.18

---

recipe/run_test.py

While the tests were running previously, the build would not be failed when the tests failed. This updates our test running step so the build will fail when the tests fail. This was tested while making this PR ( https://github.com/conda-forge/numpy-feedstock/pull/5 ) for 1.10.x support.

Set exit code based on test result

---

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml
recipe/numpy_PR_6975.diff

Fixes https://github.com/conda-forge/numpy-feedstock/issues/4
Adds NumPy 1.10.4. Going to hold on getting this merged right yet as there is some cleanup that needs to be done first. Just want to get this one out there.

Add NumPy 1.10.4

---

recipe/meta.yaml
recipe/numpy_PR_7657.diff

This updates the patch that was originally gotten as a backport of this PR ( https://github.com/numpy/numpy/pull/6975 ) present in NumPy 1.11.0 to reflect the one that was accepted in PR ( https://github.com/numpy/numpy/pull/7657 ) in `maintenance/1.10.x` branch. If there is a 1.10.5 release, we can drop this patch.

Update Backport 6975 Patch

---

.gitattributes
README.md
recipe/meta.yaml

NumPy 1.11.3 Release Notes
==========================
Numpy 1.11.3 fixes a bug that leads to file corruption when very large files
opened in append mode are used in ``ndarray.tofile``. It supports Python
versions 2.6 - 2.7 and 3.2 - 3.5. Wheels for Linux, Windows, and OS X can be
found on PyPI.

Update to 1.11.3

---

.gitattributes
.travis.yml
README.md
ci_support/run_docker_build.sh

Re-render with `conda-smithy` version `1.7.0` to update the feedstock and provide Python 3.6 support.

MNT: Re-rendered with conda-smithy 1.7.0

---

recipe/meta.yaml

```
On behalf of the NumPy team, I am pleased to announce the NumPy 1.13.0 release. This release supports Python 2.7 and 3.4-3.6 and contains many new features. It is one of the most ambitious releases in the last several years. Some of the highlights and new functions are
Highlights
- Operations like ``a + b + c`` will reuse temporaries on some platforms, resulting in less memory use and faster execution.
- Inplace operations check if inputs overlap outputs and create temporaries to avoid problems.
- New __array_ufunc__ attribute provides improved ability for classes to override default ufunc behavior.
- New np.block function for creating blocked arrays.
New functions
- New ``np.positive`` ufunc.
- New ``np.divmod`` ufunc provides more efficient divmod.
- New ``np.isnat`` ufunc tests for …
```

Update to 1.13.0

---

recipe/meta.yaml

Dropping the patch b/c it was merged upstream.
See https://github.com/numpy/numpy/releases/tag/v1.13.1

update to 1.13.1

---

recipe/meta.yaml

packages depending on numpy cannot be build with 0.2.20 which can lead
to the conda package manager installing mkl and programs crashing
randomly trying to load the mkl and failing.
Fix #64
I'm also running a check if pinning to openblas 0.2.19 fixes the CI-builds for MDAnalysis
https://github.com/MDAnalysis/mdanalysis/pull/1677

build with openblas 0.2.19

---

recipe/meta.yaml

cc @isuruf @ocefpaf 
See: https://github.com/conda-forge/scipy-feedstock/pull/75 https://github.com/conda-forge/openblas-feedstock/pull/38
Resolves a dependency conflict with the version of SciPy 1.0.0 on conda-forge.

Build with OpenBLAS 0.2.20

---

.circleci/config.yml
.travis.yml

This allows projects that want to support numpy 1.14 and python 3.4 to use conda-forge for unit-testing on Travis. Eg MDAnalysis.

build numpy 1.14 on python3.4

---

recipe/meta.yaml
recipe/numpy_distutils_ldflags.diff

I'll backport this patch to other releases if this is accepted. (The file hasn't been touched in 5 years, which makes it easy to backport.)
xref: https://github.com/numpy/numpy/issues/7427
Checklist

Fix numpy distutils ldflags overriding behaviour

---

recipe/meta.yaml

Seems i accidentally removed the blas feature.  Not having it causes older build numbers to be favored by the solver.

Readd feature

---

.ci_support/linux_c_compilergcccxx_compilergxxfortran_compilergfortranpython2.7.yaml
.ci_support/linux_c_compilergcccxx_compilergxxfortran_compilergfortranpython3.6.yaml
.ci_support/linux_c_compilergcccxx_compilergxxfortran_compilergfortranpython3.7.yaml
recipe/meta.yaml
recipe/treat-openblas-as-c.patch

Numpy 1.9 hardcodes that openblas should be treated as a FORTRAN library, but that seems to break with version 0.3 — not in Numpy itself, but when building scikit-learn, as per [its #76](https://github.com/conda-forge/scikit-learn-feedstock/pull/76). This patch fixes sklearn in local testing.

Fix scikit-learn

---

.azure-pipelines/azure-pipelines-linux.yml
.ci_support/linux_64_numpy1.16python3.6.____cpython.yaml
.ci_support/linux_64_numpy1.16python3.7.____cpython.yaml
.ci_support/linux_64_numpy1.16python3.8.____cpython.yaml
.ci_support/linux_64_numpy1.18python3.6.____73_pypy.yaml
.ci_support/linux_64_numpy1.19python3.9.____cpython.yaml
.ci_support/linux_aarch64_numpy1.16python3.6.____cpython.yaml
.ci_support/linux_aarch64_numpy1.16python3.7.____cpython.yaml
.ci_support/linux_aarch64_numpy1.16python3.8.____cpython.yaml
.ci_support/linux_aarch64_numpy1.18python3.6.____73_pypy.yaml
.ci_support/linux_aarch64_numpy1.19python3.9.____cpython.yaml
.ci_support/linux_ppc64le_numpy1.16python3.6.____cpython.yaml
.ci_support/linux_ppc64le_numpy1.16python3.7.____cpython.yaml
.ci_support/linux_ppc64le_numpy1.16python3.8.____cpython.yaml
.ci_support/linux_ppc64le_numpy1.18python3.6.____73_pypy.yaml
.ci_support/linux_ppc64le_numpy1.19python3.9.____cpython.yaml
.ci_support/osx_64_numpy1.16python3.6.____cpython.yaml
.ci_support/osx_64_numpy1.16python3.7.____cpython.yaml
.ci_support/osx_64_numpy1.16python3.8.____cpython.yaml
.ci_support/osx_64_numpy1.18python3.6.____73_pypy.yaml
.ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
.ci_support/osx_arm64_python3.8.____cpython.yaml
.ci_support/osx_arm64_python3.9.____cpython.yaml
.drone.yml
.github/CODEOWNERS
.travis.yml
README.md
conda-forge.yml
recipe/meta.yaml

The bot fleet can now run on branches if you request it from them. Enable this for `numpy` as old releases are used for building packages and should be kept uptodate with conda-forge's pinning.
Please review this and approve. I can merge myself later. I would do the following before merging so that we have new builds with the latest pinnings before we do new builds with the current migrations.
Checklist

Rerender and add as a maintainer

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.ci_support/linux_64_numpy1.16python3.6.____cpython.yaml
.ci_support/linux_64_numpy1.16python3.7.____cpython.yaml
.ci_support/linux_64_numpy1.16python3.8.____cpython.yaml
.ci_support/linux_64_numpy1.19python3.7.____73_pypy.yaml
.ci_support/linux_64_numpy1.19python3.9.____cpython.yaml
.ci_support/linux_aarch64_numpy1.19python3.7.____73_pypy.yaml
.ci_support/linux_ppc64le_numpy1.19python3.7.____73_pypy.yaml
.ci_support/migrations/pypy37.yaml
.ci_support/osx_64_numpy1.19python3.7.____73_pypy.yaml
.drone.yml
.travis.yml
README.md
recipe/meta.yaml

Checklist
I was wondering why https://github.com/conda-forge/pandas-feedstock/pull/106 had been opened by the migrator already, and couldn't find `numpy` listed anywhere in the [migration page](https://conda-forge.org/status/). Trying a manual build, but happy to close if this should be done differently.

Manual pypy3.7 migration build

---

recipe/meta.yaml

remove obsolete test skip

---

recipe/meta.yaml

NumPy does not support `setuptools >=60.0`, because that is the release that re-enabled the vendored `distutils` copy in
`setuptools`, and it has backwards compatibility issues with `numpy.distutils`. There is currently no plan to resolve those;
NumPy itself will keep this pin, and other projects are advised to migrate away from `numpy.distutils`.

Pin to `setuptools<60.0.0`

---

.azure-pipelines/azure-pipelines-win.yml
conda-forge.yml
recipe/meta.yaml

Noticed yesterday that this wasn't yet running all tests, but just those with `label='fast'`.

Run full test suite

---

recipe/meta.yaml

Against expectations, a new [release](https://github.com/numpy/numpy/releases/tag/v1.21.6) for 1.21.x. :)

numpy 1.21.6
